// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

// Map NODE_ENV values to their corresponding .env file names
const envFileByNodeEnv: Record<string, string> = {
  local: ".env.local",
  development: ".env.local",          // Use .env.local for development
  staging: ".env.staging",            // Use .env.staging for staging
  production: ".env.production",      // Use .env.production for production
  docker: ".env.docker",              // Use .env.docker for Docker environments
  test: ".env.test"                   // Use .env.test for testing
};

// Determine which environment file to load based on NODE_ENV or default to "development"
const selectedEnvFile = envFileByNodeEnv[process.env.NODE_ENV ?? "development"] ?? ".env.local";
console.log("NODE_ENV:", process.env.NODE_ENV);

// The candidate environment files to try, in priority order
const envCandidates = [selectedEnvFile, ".env"];

// Try to load the first environment file that exists from envCandidates
for (const file of envCandidates) {
  const fullPath = path.resolve(process.cwd(), file);
  if (fs.existsSync(fullPath)) {
    // Load environment variables from the file and stop after the first match
    dotenv.config({ path: fullPath });
    break;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});


// Usage
// Run with the environment you want, for example:

// NODE_ENV=staging npx prisma studio

